#!/usr/bin/env bash
set -eux
rm -rf sandbox
mkdir sandbox
echo "building schemalessd" && \
cd cmd/schemalessd && go build && \
mkdir ../../sandbox/config && \
cp schemalessd ../../sandbox && \
cd ../../ && \
cp shards.json.pg shards.json && \
cp shards.json sandbox
