#!/bin/bash
set -eux
rm -rf sandbox
mkdir sandbox
echo "building apiserver" && \
cd cmd/apiserver && go build && \
mkdir ../../sandbox/config && \
cp apiserver ../../sandbox && \
cd ../../ && \
cp shards.json sandbox
